# TypeScript
# Step 1: Pull the code
# Step 2: Install the dependencies & package
# Step 3: Collect artifacts

trigger:
  branches:
    include:
      - refs/tags/v*
      - master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.14.2'
  displayName: 'Install Node.js'

- script: |
    buildVersionString=$(node -p "require('./package.json').version")
    echo "##vso[task.setvariable variable=packageVersion;]$buildVersionString"
    yarn config set network-timeout 300000
    yarn install
    node_modules/.bin/vsce package --yarn --allow-star-activation
  displayName: 'Run yarn install and package'

- script: |
    yarn deploy
  displayName: 'Publish to Marketplace'
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
  env:
    VSCE_PAT: $(VSCE_PAT)

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(System.DefaultWorkingDirectory)/xoj-playground-$(packageVersion).vsix'
    artifactName: 'VSIX'
